In [2]:
import pandas as pd
import numpy as np
import pickle
symbol = 'S'
df = pd.read_pickle(f'C:/Users/yuhang.hou/projects/holidays/poc_backtester/data_pipeline/universal/pickle_files/{symbol}_price.pickle')
df = df[df['type']=='close']
df

              date contract  expiry_month  expiry_year   type    value
0       2025-01-01        S             8         2025  close  1032.75
3       2025-01-02        S             8         2025  close  1036.25
5       2025-01-03        S             8         2025  close  1015.50
7       2025-01-04        S             8         2025  close  1015.50
9       2025-01-05        S             8         2025  close  1015.50
...            ...      ...           ...          ...    ...      ...
241240  2014-05-14        S             5         2015  close  1237.00
241243  2014-05-15        S             5         2015  close  1230.00
241246  2014-05-16        S             5         2015  close  1233.75
241249  2014-05-19        S             5         2015  close  1249.25
241252  2014-05-20        S             5         2015  close  1242.50

[88255 rows x 6 columns]

In [3]:
business_days = list(df['date'].unique())
business_days = sorted(business_days)
business_days = [i.strftime('%Y-%m-%d') for i in business_days]

In [4]:
month_map = {1:'F',2:'G',3:'H',4:'J',5:'K',6:'M',7:'N',8:'Q',9:'U',10:'V',11:'X',12:'Z'}
df['contract_code'] = df['expiry_month'].map(month_map) + df['expiry_year'].astype(str).str[-2:]
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)
df

           contract  expiry_month  expiry_year   type    value contract_code
date
2025-01-01        S             8         2025  close  1032.75           Q25
2025-01-02        S             8         2025  close  1036.25           Q25
2025-01-03        S             8         2025  close  1015.50           Q25
2025-01-04        S             8         2025  close  1015.50           Q25
2025-01-05        S             8         2025  close  1015.50           Q25
...             ...           ...          ...    ...      ...           ...
2014-05-14        S             5         2015  close  1237.00           K15
2014-05-15        S             5         2015  close  1230.00           K15
2014-05-16        S             5         2015  close  1233.75           K15
2014-05-19        S             5         2015  close  1249.25           K15
2014-05-20        S             5         2015  close  1242.50           K15

[88255 rows x 6 columns]

In [5]:
import os
rootpath =  f'C:/Users/yuhang.hou/projects/pipeline/data/{symbol}'
if not os.path.exists(rootpath):
    os.mkdir(rootpath)
contracts = df['contract_code'].unique()
ltd = {}
for contract in contracts:
    df_contract = df[df['contract_code'] == contract].copy()
    df_contract.sort_index( inplace=True)
    df_contract = df_contract[['value']].rename(columns={'value': 'close'})
    df_contract['return'] = df_contract['close'] / df_contract['close'].shift(1) - 1
    df_contract.to_csv(rootpath + '/' + contract + '.csv')
    if contract[1:]>'26':
        continue
    ltd[contract] = df_contract.index[-1].strftime('%Y-%m-%d')
    
ltd

{'Q25': '2025-07-31',
 'F26': '2026-01-19',
 'Q26': '2026-02-10',
 'H25': '2025-02-28',
 'U25': '2025-08-29',
 'H26': '2026-02-10',
 'K25': '2025-04-30',
 'K26': '2026-02-10',
 'N25': '2025-06-30',
 'N26': '2026-02-10',
 'U26': '2026-02-10',
 'X25': '2025-10-31',
 'X26': '2026-02-10',
 'X01': '2001-10-31',
 'F00': '1999-12-30',
 'U03': '2003-08-29',
 'Q05': '2005-07-29',
 'U05': '2005-08-31',
 'X03': '2003-10-31',
 'F09': '2008-12-31',
 'N07': '2007-06-29',
 'N10': '2010-06-30',
 'Q10': '2010-07-30',
 'H14': '2014-02-28',
 'F13': '2012-12-31',
 'X11': '2011-10-31',
 'N16': '2016-06-30',
 'K15': '2015-04-30',
 'N18': '2018-06-29',
 'K17': '2017-04-28',
 'Q19': '2019-07-31',
 'U20': '2020-08-31',
 'X21': '2021-10-29',
 'F23': '2022-12-30',
 'H24': '2024-02-29',
 'H00': '2000-02-29',
 'N15': '2015-06-30',
 'H13': '2013-02-28',
 'H09': '2009-02-27',
 'X20': '2020-10-30',
 'F02': '2001-12-31',
 'U19': '2019-08-30',
 'Q07': '2007-07-31',
 'H23': '2023-02-28',
 'X05': '2005-10-31',
 'U10': '2010-08-31',
 'Q16': '2016-07-29',
 'K00': '2000-04-28',
 'K09': '2009-04-30',
 'F04': '2003-12-31',
 'F12': '2011-12-30',
 'F22': '2021-12-31',
 'K14': '2014-04-30',
 'H02': '2002-02-28',
 'U07': '2007-08-31',
 'K13': '2013-04-30',
 'F21': '2020-12-31',
 'N00': '2000-06-30',
 'Q18': '2018-07-31',
 'Q15': '2015-07-31',
 'F06': '2005-12-29',
 'X19': '2019-10-31',
 'X10': '2010-10-29',
 'H04': '2004-02-27',
 'U16': '2016-08-31',
 'N09': '2009-06-30',
 'K23': '2023-04-28',
 'H12': '2012-02-29',
 'K02': '2002-04-30',
 'X07': '2007-10-31',
 'H22': '2022-02-28',
 'H06': '2006-02-28',
 'N14': '2014-06-30',
 'N13': '2013-06-28',
 'Q00': '2000-07-31',
 'U15': '2015-08-31',
 'K04': '2004-04-30',
 'H21': '2021-02-26',
 'U18': '2018-08-31',
 'N23': '2023-06-30',
 'X16': '2016-10-31',
 'F20': '2019-12-31',
 'F08': '2007-12-31',
 'F11': '2010-12-31',
 'K06': '2006-04-28',
 'N02': '2002-06-28',
 'K12': '2012-04-30',
 'K22': '2022-04-29',
 'N04': '2004-06-30',
 'U00': '2000-08-31',
 'Q09': '2009-07-30',
 'Q14': '2014-07-31',
 'X18': '2018-10-31',
 'Q13': '2013-07-31',
 'H08': '2008-02-29',
 'H20': '2020-02-28',
 'X00': '2000-10-31',
 'X15': '2015-10-30',
 'Q23': '2023-07-31',
 'N06': '2006-06-30',
 'Q02': '2002-07-31',
 'N22': '2022-06-30',
 'Q04': '2004-07-30',
 'K08': '2008-04-30',
 'F17': '2016-12-30',
 'N12': '2012-06-29',
 'H11': '2011-02-28',
 'U09': '2009-08-31',
 'U23': '2023-08-31',
 'U13': '2013-08-30',
 'U02': '2002-08-30',
 'U14': '2014-08-29',
 'U04': '2004-08-31',
 'K20': '2020-04-30',
 'F19': '2018-12-31',
 'Q06': '2006-07-31',
 'F16': '2015-12-31',
 'N08': '2008-06-30',
 'Q22': '2022-07-29',
 'X02': '2002-10-31',
 'X14': '2014-10-31',
 'F01': '2000-12-29',
 'N17': '2017-06-30',
 'X09': '2009-10-30',
 'X04': '2004-10-29',
 'H17': '2017-02-28',
 'Q12': '2012-07-31',
 'X13': '2013-10-31',
 'H16': '2016-02-29',
 'U06': '2006-08-31',
 'X23': '2023-10-31',
 'N20': '2020-06-30',
 'H19': '2019-02-28',
 'K11': '2011-04-29',
 'H01': '2001-02-28',
 'Q08': '2008-07-31',
 'X06': '2006-10-31',
 'F14': '2013-12-31',
 'F07': '2006-12-29',
 'F10': '2009-12-31',
 'U22': '2022-08-31',
 'F24': '2023-12-29',
 'U12': '2012-08-31',
 'F03': '2002-12-31',
 'K16': '2016-04-29',
 'K21': '2021-04-30',
 'U08': '2008-08-29',
 'K19': '2019-04-30',
 'Q20': '2020-07-31',
 'F05': '2004-12-30',
 'H07': '2007-02-28',
 'K24': '2024-04-30',
 'K01': '2001-04-30',
 'H03': '2003-02-28',
 'K07': '2007-04-30',
 'H10': '2010-02-26',
 'N11': '2011-06-30',
 'F15': '2014-12-31',
 'X22': '2022-10-31',
 'X08': '2008-10-31',
 'X12': '2012-10-31',
 'K03': '2003-04-30',
 'N01': '2001-06-29',
 'H05': '2005-02-28',
 'N19': '2019-06-28',
 'Q11': '2011-07-29',
 'K10': '2010-04-30',
 'N21': '2021-06-30',
 'N03': '2003-06-30',
 'U11': '2011-08-31',
 'N24': '2024-06-28',
 'K05': '2005-04-29',
 'Q01': '2001-07-31',
 'N05': '2005-06-30',
 'U01': '2001-08-31',
 'Q03': '2003-07-31',
 'Q21': '2021-07-30',
 'Q24': '2024-07-31',
 'U21': '2021-08-31',
 'U24': '2024-08-30',
 'Q17': '2017-07-31',
 'X24': '2024-10-31',
 'F25': '2024-12-31',
 'U17': '2017-08-31',
 'X17': '2017-10-31',
 'F18': '2017-12-29',
 'H18': '2018-02-28',
 'K18': '2018-04-30',
 'H15': '2015-02-27'}

In [7]:
import json
with open('last_trading_day.json', 'w') as f:
    json.dump(ltd, f)